/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface Voting extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Voting;
  clone(): Voting;
  methods: {
    votesReceived(arg0: string | number[]): NonPayableTransactionObject<string>;

    candidateList(
      arg0: number | string | BN
    ): NonPayableTransactionObject<string>;

    totalVotesFor(
      candidate: string | number[]
    ): NonPayableTransactionObject<string>;

    voteForCandidate(
      candidate: string | number[]
    ): NonPayableTransactionObject<void>;

    validCandidate(
      candidate: string | number[]
    ): NonPayableTransactionObject<boolean>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
